name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of Release'
        type: choice
        default: 'fix'
        options:
          - 'feat'
          - 'fix'
      reason:
        description: 'Reason for manual release'
        required: true
        type: string
      confirm:
        description: 'Check this box to confirm you want to release'
        required: true
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
        env:
          CI: true

      - name: Build
        run: npm run build && cd dist && ls -la

      - name: Run manual release
        run: |
          echo "Forcing release with a custom message"
          cd dist
          git config --global user.email "eg-oss-ci@expediagroup.com"
          git config --global user.name "eg-oss-ci"
          git add .
          git commit --allow-empty -m "${{ github.event.inputs.release-type }}: ${{ github.event.inputs.reason }}"
          npx semantic-release --release-as ${{ github.event.inputs.release-type }} --no-ci
          git revert HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
