name: Release
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
        env:
          CI: true

      - name: Build
        run: npm run build && cd dist && ls -la

      - name: Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          working_directory: dist
          extra_plugins: |
            conventional-changelog-conventionalcommits@9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
