name: Release
on:
  push:
    branches:
      - main
      - test
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
        env:
          CI: true

      - name: Build
        run: npm run build && cd dist && ls -la

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd dist && npx semantic-release
